### ISSUE TITLE
undefined symbol: _intel_fast_memset

### ISSUE THREAD

**Issue by AaronDavidSchneider** [fortran-lang/setup-fortran#46] opened 2023-10-27 12:27 UTC
```
Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/test_env/bin/exorad_opac_create", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/runner/work/exorad/exorad/exorad/exorad_opac/bin/exorad_opac_create", line 11, in <module>
    from exorad_opac import wrap_standard_preprocessing
  File "/home/runner/work/exorad/exorad/exorad/exorad_opac/exorad_opac/__init__.py", line 2, in <module>
    from .preprocessing import PRTPreprocessingWrapper, PreprocessingWrapper
  File "/home/runner/work/exorad/exorad/exorad/exorad_opac/exorad_opac/preprocessing.py", line 4, in <module>
    from .chemistry import calc_eq_abunds
  File "/home/runner/work/exorad/exorad/exorad/exorad_opac/exorad_opac/chemistry.py", line 4, in <module>
    from petitRADTRANS.poor_mans_nonequ_chem import interpol_abundances
  File "/usr/share/miniconda3/envs/test_env/lib/python3.10/site-packages/petitRADTRANS/__init__.py", line 18, in <module>
    from petitRADTRANS.radtrans import Radtrans
  File "/usr/share/miniconda3/envs/test_env/lib/python3.10/site-packages/petitRADTRANS/radtrans.py", line 14, in <module>
    from petitRADTRANS import _read_opacities
  File "/usr/share/miniconda3/envs/test_env/lib/python3.10/site-packages/petitRADTRANS/_read_opacities.py", line 9, in <module>
    from petitRADTRANS import fort_input as fi
ImportError: /usr/share/miniconda3/envs/test_env/lib/python3.10/site-packages/petitRADTRANS/fort_input.cpython-[31](https://github.com/exorad/exorad/actions/runs/6666744607/job/18118863964?pr=45#step:15:32)0-x86_64-linux-gnu.so: undefined symbol: _intel_fast_memset
```

I am trying to use this actions for one of my fortran codes. In this action, I have a pip install that installs a python code with interface to a fortran code (compiled with f2py).

All of that works fine, but executing the compiled binary raises the error `undefined symbol: _intel_fast_memset`.

This is how I set up the intel compilers:
```
      - name: Setup intel compilers
        uses: fortran-lang/setup-fortran@v1
        id: setup-ifort
        with:
          compiler: 'intel'
          version: '2023.2'
        if: ${{ matrix.use_ifort }}
```

**Comment by wpbonelli** [comment] 2023-10-27 15:42
It looks like your f2py extension module was built with the gnu toolchain. Perhaps try building it with intel or build your target with gnu?

**Comment by AaronDavidSchneider** [comment] 2023-10-30 09:36
Thanks for the reply and the insights. I went back and tried also ifort from intel-classic and also, possibly more important also updated the anaconda channel priority to install numpy (which hosts f2py) from intel instead of conda-forge.
While I can confirm that numpy is now from intel and not from conda-forge, the issue is still the same.

Only the intel function that is missing is a different one now:
ImportError: /usr/share/miniconda3/envs/test_env/lib/python3.10/site-packages/petitRADTRANS/fort_input.cpython-310-x86_64-linux-gnu.so: undefined symbol: __intel_sse2_strcpy

**Comment by wpbonelli** [comment] 2023-10-30 10:18
I think what you want is an extension module built with intel. I don't think it should matter what numpy was built with. In the new error message I still see `...-linux-gnu.so`. Does this not indicate the .so was compiled with gnu? F2py should be able to build an extension with any of several Fortran compilers regardless of where numpy came from and how it was built, right? See the third bullet here https://numpy.org/doc/stable/f2py/f2py.getting-started.html#three-ways-to-wrap-getting-started

I am new to F2py so forgive me if I'm missing something obvious

**Comment by AaronDavidSchneider** [comment] 2023-10-31 05:42
Thanks again for your reply. I honestly have no idea, why f2py would choose the gnu compilers instead. But it looks to me as if f2py can not find the intel compilers, even if I specify them.

I went back and now install one api manually instead. I don't have the issue there.

**Comment by wpbonelli** [comment] 2023-10-31 05:58
Is this a public repo? If you could link a sample run I'd be interested to take a look.

**Comment by AaronDavidSchneider** [comment] 2023-10-31 07:34
It is a private repo, which I am not allowed to make public... But I would be happy to talk over it and show it to you over a zoom call, if you are interested?

**Comment by wpbonelli** [comment] 2023-10-31 11:15
Thanks but it would be better if you could reproduce the error as simply as you can in a throwaway public repository. Presumably that is possible without revealing details of your project?

**Comment by AaronDavidSchneider** [comment] 2023-10-31 16:40
That's a good idea. I will try to do that once I find the time.

**Comment by AaronDavidSchneider** [comment] 2023-11-01 08:49
Here we go:
https://github.com/AaronDavidSchneider/test-fortran-conda

It is a minimal reproduced example of what I am doing:

A fortran function wrapped in python and called in python, compiled using f2py.

The ci does the following:
1. clone repo
2. install compilers
3. install anaconda
4. install python pkg (which invokes f2py to compile the fortran code)
5. invoke a python script that calls the fortran function

The structure of the minimal python pkg is the following:
- The fortran function is defined in simple_routine.f90
- The python wrapper of the fortran function is defined in add.py
- The python file to test the code is in the bin folder, which install this script into the PATH
- The setup.py file is used to install the minimal python pkg and defines the fortran file as python (sub)module

**Comment by wpbonelli** [comment] 2023-11-02 17:09
I had a look. So the issue is `setuptools` needs to know which compiler to use. By default I guess it tries `gfortran`. You can either provide `--fcompiler=intelem` to `python setup.py build` or `build_ext` (`intelem` is intel 64-bit, to see available options give it a garbage value and it will warn and list them), or in `setup.cfg`:

```
[build_ext]
fcompiler = intelem
```

Sample run: https://github.com/wpbonelli/test-fortran-conda/actions/runs/6735634307/job/18309235744

Note the modified step in `build_testing.yml` conditional on `$FC`. Generally using `setup.py` directly is not recommended but I'm not sure what the incantation is to get `pip install` to pass the compiler selection through if you must pick one dynamically.

I'm going to close this issue as python/f2py concerns are beyond the scope of this action, but if you make further progress please feel free to share as others may have similar problems. Thanks for raising, this was instructive!

References:

* https://stackoverflow.com/questions/55373559/numpy-distutils-specify-intel-fortran-compiler-in-setup-py

**Closed by wpbonelli** 2023-11-02 17:09 UTC
